Presentation/SmartStore.Web/Models/Common/AccountDropdownModel.cs
using System.ComponentModel.DataAnnotations;
using SmartStore.Web.Framework;
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Common
{
    public partial class AccountDropdownModel : EntityModelBase
    {
        public string Name { get; set; }
        public bool IsAuthenticated { get; set; }
        public bool DisplayAdminLink { get; set; }
        public bool ShoppingCartEnabled { get; set; }
        public int ShoppingCartItems { get; set; }

        public bool WishlistEnabled { get; set; }
        public int WishlistItems { get; set; }

        public bool AllowPrivateMessages { get; set; }
        public string UnreadPrivateMessages { get; set; }
        public string AlertMessage { get; set; }

        [SmartResourceDisplayName("Account.Login.Fields.Email")]
        public string Email { get; set; }

        public bool UsernamesEnabled { get; set; }

        [SmartResourceDisplayName("Account.Login.Fields.UserName")]
        public string Username { get; set; }

        [DataType(DataType.Password)]
        [SmartResourceDisplayName("Account.Login.Fields.Password")]
        public string Password { get; set; }

        [SmartResourceDisplayName("Account.Login.Fields.RememberMe")]
        public bool RememberMe { get; set; }
    }
}

Presentation/SmartStore.Web/Models/Common/CompareDropdownModel.cs
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Common
{
    public partial class CompareDropdownModel : EntityModelBase
    {
        public string Name { get; set; }
    }
}

Presentation/SmartStore.Web/Controllers/CatalogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel.Syndication;
using System.Web.Mvc;
using SmartStore.Core;
using SmartStore.Core.Caching;
using SmartStore.Core.Domain.Catalog;
using SmartStore.Core.Domain.Customers;
using SmartStore.Core.Domain.Media;
using SmartStore.Core.Security;
using SmartStore.Services.Catalog;
using SmartStore.Services.Common;
using SmartStore.Services.Localization;
using SmartStore.Services.Media;
using SmartStore.Services.Orders;
using SmartStore.Services.Search;
using SmartStore.Services.Security;
using SmartStore.Services.Seo;
using SmartStore.Services.Stores;
using SmartStore.Utilities;
using SmartStore.Web.Framework.Controllers;
using SmartStore.Web.Framework.Modelling;
using SmartStore.Web.Framework.Seo;
using SmartStore.Web.Framework.UI;
using SmartStore.Web.Infrastructure.Cache;
using SmartStore.Web.Models.Catalog;

namespace SmartStore.Web.Controllers
{
    public partial class CatalogController : PublicControllerBase
    {
        private readonly ICategoryService _categoryService;
        private readonly IManufacturerService _manufacturerService;
        private readonly IProductService _productService;
        private readonly ICategoryTemplateService _categoryTemplateService;
        private readonly IManufacturerTemplateService _manufacturerTemplateService;
        private readonly IOrderReportService _orderReportService;
        private readonly IProductTagService _productTagService;
        private readonly IRecentlyViewedProductsService _recentlyViewedProductsService;
        private readonly IGenericAttributeService _genericAttributeService;
        private readonly IAclService _aclService;
        private readonly IStoreMappingService _storeMappingService;
        private readonly ICatalogSearchService _catalogSearchService;
        private readonly MediaSettings _mediaSettings;
        private readonly CatalogSettings _catalogSettings;
        private readonly ICompareProductsService _compareProductsService;
        private readonly CatalogHelper _helper;
        private readonly IBreadcrumb _breadcrumb;

        public CatalogController(
            ICategoryService categoryService,
            IManufacturerService manufacturerService,
            IProductService productService,
            ICategoryTemplateService categoryTemplateService,
            IManufacturerTemplateService manufacturerTemplateService,
            IOrderReportService orderReportService,
            IProductTagService productTagService,
            IRecentlyViewedProductsService recentlyViewedProductsService,
            ICompareProductsService compareProductsService,
            IGenericAttributeService genericAttributeService,
            IAclService aclService,
            IStoreMappingService storeMappingService,
            ICatalogSearchService catalogSearchService,
            MediaSettings mediaSettings,
            CatalogSettings catalogSettings,
            CatalogHelper helper,
            IBreadcrumb breadcrumb)
        {
            _categoryService = categoryService;
            _manufacturerService = manufacturerService;
            _productService = productService;
            _categoryTemplateService = categoryTemplateService;
            _manufacturerTemplateService = manufacturerTemplateService;
            _orderReportService = orderReportService;
            _productTagService = productTagService;
            _recentlyViewedProductsService = recentlyViewedProductsService;
            _compareProductsService = compareProductsService;
            _genericAttributeService = genericAttributeService;
            _aclService = aclService;
            _storeMappingService = storeMappingService;
            _catalogSearchService = catalogSearchService;
            _mediaSettings = mediaSettings;
            _catalogSettings = catalogSettings;
            _helper = helper;
            _breadcrumb = breadcrumb;
        }

        #region Categories

        [RewriteUrl(SslRequirement.No)]
        public ActionResult Category(int categoryId, CatalogSearchQuery query)
        {
            var category = _categoryService.GetCategoryById(categoryId);
            if (category == null || category.Deleted)
                return HttpNotFound();

            // Check whether the current user has a "Manage catalog" permission.
            // It allows him to preview a category before publishing.
            if (!category.Published && !Services.Permissions.Authorize(Permissions.Catalog.Category.Read))
                return HttpNotFound();

            // ACL (access control list).
            if (!_aclService.Authorize(category))
                return HttpNotFound();

            // Store mapping.
            if (!_storeMappingService.Authorize(category))
                return HttpNotFound();

            var store = Services.StoreContext.CurrentStore;
            var customer = Services.WorkContext.CurrentCustomer;

            // 'Continue shopping' URL.
            if (!Services.WorkContext.CurrentCustomer.IsSystemAccount)
            {
                _genericAttributeService.SaveAttribute(customer, SystemCustomerAttributeNames.LastContinueShoppingPage, Services.WebHelper.GetThisPageUrl(false), store.Id);
            }

            var model = category.ToModel();
            if (query.IsSubPage && !_catalogSettings.ShowDescriptionInSubPages)
            {
                model.Description.ChangeValue(string.Empty);
                model.BottomDescription.ChangeValue(string.Empty);
            }

            model.PictureModel = _helper.PrepareCategoryPictureModel(category, model.Name);

            // Category breadcrumb.
            if (_catalogSettings.CategoryBreadcrumbEnabled)
            {
                _helper.GetBreadcrumb(_breadcrumb, ControllerContext);
            }

            // Products.
            var catIds = new int[] { categoryId };
            if (_catalogSettings.ShowProductsFromSubcategories)
            {
                // Include subcategories.
                catIds = catIds.Concat(_helper.GetChildCategoryIds(categoryId)).ToArray();
            }

            query.WithCategoryIds(_catalogSettings.IncludeFeaturedProductsInNormalLists ? (bool?)null : false, catIds);

            var searchResult = _catalogSearchService.Search(query);
            model.SearchResult = searchResult;

            var mappingSettings = _helper.GetBestFitProductSummaryMappingSettings(query.GetViewMode());
            model.Products = _helper.MapProductSummaryModel(searchResult.Hits, mappingSettings);

            model.SubCategoryDisplayType = _catalogSettings.SubCategoryDisplayType;

            var customerRolesIds = customer.CustomerRoleMappings
                .Select(x => x.CustomerRole)
                .Where(x => x.Active)
                .Select(x => x.Id)
                .ToList();

            var pictureSize = _mediaSettings.CategoryThumbPictureSize;
            var fallbackType = _catalogSettings.HideCategoryDefaultPictures ? FallbackPictureType.NoFallback : FallbackPictureType.Entity;

            var hideSubCategories = _catalogSettings.SubCategoryDisplayType == SubCategoryDisplayType.Hide
                || (_catalogSettings.SubCategoryDisplayType == SubCategoryDisplayType.AboveProductList && query.IsSubPage && !_catalogSettings.ShowSubCategoriesInSubPages);
            var hideFeaturedProducts = _catalogSettings.IgnoreFeaturedProducts || (query.IsSubPage && !_catalogSettings.IncludeFeaturedProductsInSubPages);

            // Subcategories.
            if (!hideSubCategories)
            {
                var subCategories = _categoryService.GetAllCategoriesByParentCategoryId(categoryId);
                model.SubCategories = _helper.MapCategorySummaryModel(subCategories, pictureSize);
            }

            // Featured Products.
            if (!hideFeaturedProducts)
            {
                CatalogSearchResult featuredProductsResult = null;

                string cacheKey = ModelCacheEventConsumer.CATEGORY_HAS_FEATURED_PRODUCTS_KEY.FormatInvariant(categoryId, string.Join(",", customerRolesIds), store.Id);
                var hasFeaturedProductsCache = Services.Cache.Get<bool?>(cacheKey);

                var featuredProductsQuery = new CatalogSearchQuery()
                    .VisibleOnly(customer)
                    .WithVisibility(ProductVisibility.Full)
                    .WithCategoryIds(true, categoryId)
                    .HasStoreId(Services.StoreContext.CurrentStore.Id)
                    .WithLanguage(Services.WorkContext.WorkingLanguage)
                    .WithCurrency(Services.WorkContext.WorkingCurrency);

                if (!hasFeaturedProductsCache.HasValue)
                {
                    featuredProductsResult = _catalogSearchService.Search(featuredProductsQuery);
                    hasFeaturedProductsCache = featuredProductsResult.TotalHitsCount > 0;
                    Services.Cache.Put(cacheKey, hasFeaturedProductsCache, TimeSpan.FromHours(6));
                }

                if (hasFeaturedProductsCache.Value && featuredProductsResult == null)
                {
                    featuredProductsResult = _catalogSearchService.Search(featuredProductsQuery);
                }

                if (featuredProductsResult != null)
                {
                    var featuredProductsmappingSettings = _helper.GetBestFitProductSummaryMappingSettings(ProductSummaryViewMode.Grid);
                    model.FeaturedProducts = _helper.MapProductSummaryModel(featuredProductsResult.Hits, featuredProductsmappingSettings);
                }
            }

            // Prepare paging/sorting/mode stuff.
            _helper.MapListActions(model.Products, category, _catalogSettings.DefaultPageSizeOptions);

            // Template.
            var templateCacheKey = string.Format(ModelCacheEventConsumer.CATEGORY_TEMPLATE_MODEL_KEY, category.CategoryTemplateId);

Presentation/SmartStore.Web/Controllers/MenuController.cs
using System;
using System.Web.Mvc;
using SmartStore.Core.Domain.Catalog;
using SmartStore.Core.Security;
using SmartStore.Web.Framework.Controllers;
using SmartStore.Web.Framework.UI;

namespace SmartStore.Web.Controllers
{
    public partial class MenuController : PublicControllerBase
    {
        private readonly IMenuService _menuService;
        private readonly IBreadcrumb _breadcrumb;
        private readonly CatalogSettings _catalogSettings;
        private readonly CatalogHelper _catalogHelper;

        public MenuController(
            IMenuService menuService,
            IBreadcrumb breadcrumb,
            CatalogSettings catalogSettings,
            CatalogHelper catalogHelper)
        {
            _menuService = menuService;
            _breadcrumb = breadcrumb;
            _catalogSettings = catalogSettings;
            _catalogHelper = catalogHelper;
        }

        [ChildActionOnly]
        public ActionResult Menu(string name, string template = null)
        {
            var menu = _menuService.GetMenu(name);

            if (menu == null)
                return new EmptyResult();

            var model = menu.CreateModel(template, ControllerContext);

            return Menu(model);
        }

        [ChildActionOnly, ActionName("MenuFromModel")]
        public ActionResult Menu(MenuModel model)
        {
            Guard.NotNull(model, nameof(model));

            var viewName = (model.Template ?? model.Name);
            if (viewName[0] != '~' && !viewName.StartsWith("Menus/", StringComparison.OrdinalIgnoreCase))
            {
                viewName = "Menus/" + viewName;
            }

            return this.RootActionPartialView(viewName, model);
        }

        [ChildActionOnly]
        public ActionResult Breadcrumb()
        {
            if (_breadcrumb.Trail == null || _breadcrumb.Trail.Count == 0)
            {
                return new EmptyResult();
            }

            return PartialView(_breadcrumb.Trail);
        }

        #region OffCanvasMenu 

        /// <summary>
        /// Called by AJAX to get the an OffCanvas layer (either the root "home" or a "submenu" layer)
        /// </summary>
        /// <param name="currentNodeId">Id of currently selected node/page from sm:pagedata meta tag</param>
        /// <param name="targetNodeId">Id of the parent node to which should be navigated in the OffCanvasMenu (actually the node which was clicked)</param>
        [HttpPost]
        public ActionResult OffCanvas(string currentNodeId, string targetNodeId)
        {
            bool allowNavigation = Services.Permissions.Authorize(Permissions.System.AccessShop);

            ViewBag.AllowNavigation = allowNavigation;
            ViewBag.ShowNodes = allowNavigation;
            ViewBag.ShowBrands = allowNavigation
                && _catalogSettings.ShowManufacturersInOffCanvas == true
                && _catalogSettings.ManufacturerItemsToDisplayInOffcanvasMenu > 0;

            if (!allowNavigation)
            {
                return PartialView("OffCanvas.Home", null);
            }

            var model = PrepareMenuModel(currentNodeId, targetNodeId);
            if (model == null)
            {
                return new EmptyResult();
            }

            var selectedNode = model.SelectedNode;
            var isHomeLayer = selectedNode.IsRoot || (selectedNode.Depth == 1 && selectedNode.IsLeaf);

            var templateName = isHomeLayer
                // Render home layer, if parent node is either home or a direct child of home
                ? "OffCanvas.Home"
                // Render a submenu
                : "OffCanvas.Menu";

            return PartialView(templateName, model);
        }

        /// <summary>
        /// Prepares the menu for given parent node 'targetNodeId' with current node 'currentNodeId'
        /// </summary>
        /// <param name="currentNodeId">Id of currently selected node/page from sm:pagedata meta tag.</param>
        /// <param name="targetNodeId">Id of the parent node to which should be navigated in the OffCanvasMenu (actually the node which was clicked).</param>
        [NonAction]
        protected MenuModel PrepareMenuModel(string currentNodeId, string targetNodeId)
        {
            var menu = _menuService.GetMenu("Main");
            if (menu == null)
            {
                return null;
            }

            object nodeId = ConvertNodeId(targetNodeId);

            var model = new MenuModel
            {
                Name = "offcanvas",
                Root = menu.Root,
                SelectedNode = IsNullNode(nodeId)
                    ? menu.Root
                    : menu.Root.SelectNodeById(nodeId)
            };
            menu.ResolveElementCounts(model.SelectedNode, false);

            if (currentNodeId == targetNodeId)
            {
                ViewBag.CurrentNode = model.SelectedNode;
            }
            else
            {
                nodeId = ConvertNodeId(currentNodeId);
                if (!IsNullNode(nodeId))
                {
                    ViewBag.CurrentNode = menu.Root.SelectNodeById(nodeId);
                }
            }

            return model;
        }

        [HttpPost]
        public ActionResult OffCanvasBrands()
        {
            var model = _catalogHelper.PrepareManufacturerNavigationModel(_catalogSettings.ManufacturerItemsToDisplayInOffcanvasMenu);
            return PartialView("OffCanvas.Brands", model);
        }

        #endregion

        #region Utils

        private static object ConvertNodeId(string source)
        {
            int? intId = int.TryParse(source, out var id) ? id : (int?)null;
            return (intId.HasValue ? (object)intId.Value : (object)source);
        }

        private static bool IsNullNode(object source)
        {
            return source == null || object.Equals(0, source) || object.Equals(string.Empty, source);
        }

        #endregion
    }
}

Presentation/SmartStore.Web/Views/Common/Partials/CurrencySelector.cshtml
@model CurrencySelectorModel
@using SmartStore.Web.Models.Common;
@using SmartStore.Core;
@using SmartStore.Core.Infrastructure;
@using SmartStore.Core.Infrastructure.DependencyManagement;
@using System.Globalization;

@if (Model.AvailableCurrencies.Count > 1)
{
    var webHelper = EngineContext.Current.Resolve<IWebHelper>();
    var activeCurr = Model.AvailableCurrencies.Where(x => x.Id == Model.CurrentCurrencyId).FirstOrDefault();

    <div class="dropdown currency-selector">
        <a class="menubar-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#">
			<span class="pr-1">@activeCurr.ISOCode</span>
			<span class="lrm">(@activeCurr.Symbol)</span>
            <i class="fa fa-angle-down"></i>
        </a>

        <div class="dropdown-menu">
            @foreach (var curr in Model.AvailableCurrencies)
            {
                var href = webHelper.ModifyQueryString(Url.RouteUrl("ChangeCurrency", new { customercurrency = curr.Id }), "returnUrl=" + HttpUtility.UrlEncode(HttpContext.Current.Request.RawUrl), null);

                <a href="@href" class="dropdown-item@(curr.Id == activeCurr.Id ? " disabled" : "")" title="@curr.Name" rel="nofollow" 
                   data-selected="@(curr.Equals(activeCurr) ? "true" : "false")" data-abbreviation="@("{0} ({1})".FormatWith(curr.ISOCode, curr.Symbol))">
                    <span>@curr.Name</span>
                    <span class="abbreviation"> - @curr.ISOCode <span class="lrm">(@curr.Symbol)</span></span>
                </a>
            }
        </div>
    </div>

	<script>
		$(function () {
			$(".currency-selector .dropdown-item.disabled").on('click', function (e) {
				e.preventDefault();
            });
        });
	</script>
}

Presentation/SmartStore.Web/Views/Common/Partials/Favicon.cshtml
@model FaviconModel

@using SmartStore.Web.Models.Common;

@if (Model.FavIcon != null)
{
    <link rel="shortcut icon" href="@Url.Media(Model.FavIcon, 0, null, false)?v=@SmartStoreVersion.CurrentVersion" />
}

@if (Model.PngIcon != null)
{
    @*16x16 (browser tabs), 32x32 (Taskbar), 96x96 (Desktop), 196x196 (Android Chrome)*@
    <!-- png icons -->
    <link rel="icon" type="image/png" sizes="16x16" href="@Url.Media(Model.PngIcon, 16, null, false)">
    <link rel="icon" type="image/png" sizes="32x32" href="@Url.Media(Model.PngIcon, 32, null, false)">
    <link rel="icon" type="image/png" sizes="96x96" href="@Url.Media(Model.PngIcon, 96, null, false)">
    <link rel="icon" type="image/png" sizes="196x196" href="@Url.Media(Model.PngIcon, 196, null, false)">
}

@if (Model.AppleTouchIcon != null)
{
    <!-- Apple touch icons -->
    <link rel="apple-touch-icon" sizes="57x57" href="@Url.Media(Model.AppleTouchIcon, 57, null, false)">
    <link rel="apple-touch-icon" sizes="60x60" href="@Url.Media(Model.AppleTouchIcon, 60, null, false)">
    <link rel="apple-touch-icon" sizes="72x72" href="@Url.Media(Model.AppleTouchIcon, 72, null, false)">
    <link rel="apple-touch-icon" sizes="76x76" href="@Url.Media(Model.AppleTouchIcon, 76, null, false)">
    <link rel="apple-touch-icon" sizes="114x114" href="@Url.Media(Model.AppleTouchIcon, 114, null, false)">
    <link rel="apple-touch-icon" sizes="120x120" href="@Url.Media(Model.AppleTouchIcon, 120, null, false)">
    <link rel="apple-touch-icon" sizes="144x144" href="@Url.Media(Model.AppleTouchIcon, 144, null, false)">
    <link rel="apple-touch-icon" sizes="152x152" href="@Url.Media(Model.AppleTouchIcon, 152, null, false)">
    <link rel="apple-touch-icon" sizes="180x180" href="@Url.Media(Model.AppleTouchIcon, 180, null, false)">
}

@if (Model.MsTileIcon != null)
{
    <!-- Microsoft tiles -->
    if (Model.MsTileColor.HasValue())
    {
        <meta name="msapplication-TileColor" content="@Model.MsTileColor">
    }
    <meta name="msapplication-TileImage" content="@Url.Media(Model.MsTileIcon, 144, null, false)">
    <meta name="msapplication-config" content="@Url.Content("~/browserconfig.xml")" />
}

Presentation/SmartStore.Web/Views/Common/Partials/GdprConsent.cshtml
@model SmartStore.Web.Models.Common.GdprConsentModel
@{
	Layout = "";
	var id = "gdpr-consent-" + CommonHelper.GenerateRandomInteger();
}

<div class="form-group row gdpr-consent @(Model.SmallDisplay ? "small" : "")">
	<div class="col form-control-plaintext">
		<div class="form-check">
			@Html.CheckBoxFor(model => model.GdprConsent, new { @class = "form-check-input gdpr-consent-check", @id = id })
			<label class="form-check-label" for="@id">
				@Html.Raw(T("Gdpr.Consent.DetailText" + (Model.SmallDisplay ? ".Small" : "")).Text.FormatWith(Url.Topic("privacyinfo")))
			</label>
		</div>
		@Html.ValidationMessageFor(model => model.GdprConsent)
	</div>
</div>	

Presentation/SmartStore.Web/Views/Common/Partials/JavaScriptDisabledWarning.cshtml
@model dynamic
<noscript>
    <div class="noscript">
        <p>
            <strong>JavaScript seem to be disabled in your browser.</strong></p>
        <p>
            You must have JavaScript enabled in your browser to utilize the functionality of
            this website.</p>
    </div>
</noscript>

Presentation/SmartStore.Web/Views/Common/Partials/ShopBar.Tools.cshtml
@model ShopBarModel
@using SmartStore.Web.Models.Common;
@{ 
	if (IsStoreClosed)
	{
		return;
	}

	string accountUrl = Model.IsAuthenticated ? Url.Action("Info", "Customer") : Url.RouteUrl("Login", new { returnUrl = Request.RawUrl });
	var labelStyle = GetThemeVariable<string>("shopbar-label", "warning");
	var isRtl = this.WorkContext.WorkingLanguage.Rtl;
}

<div class="shopbar-col shopbar-tools" data-summary-href="@Url.Action("CartSummary", "ShoppingCart", new { cart = Model.ShoppingCartEnabled, wishlist = Model.WishlistEnabled, compare = Model.CompareProductsEnabled })">

	<!-- Hamburger Menu -->
	<div class="shopbar-tool d-lg-none" id="shopbar-menu">
		<a class="shopbar-button" href="#" data-toggle="offcanvas" data-autohide="true" data-placement="@(isRtl ? "right" : "left")" data-fullscreen="false" data-disablescrolling="true" data-target="#offcanvas-menu">
			<span class="shopbar-button-icon">
				<i class="icm icm-menu"></i>
			</span>
			<span class="shopbar-button-label-sm">
				@T("Common.Menu")
			</span>
		</a>
	</div>

    @{ Html.RenderWidget("shopbar_tools_before"); }

	<!-- User -->
	<div class="shopbar-tool d-lg-none" id="shopbar-user">
		<a class="shopbar-button" href="@accountUrl">
			<span class="shopbar-button-icon">
				<i class="icm icm-user"></i>
			</span>
			<span class="shopbar-button-label-sm">
				@T(Model.IsAuthenticated ? "Account.MyAccount" : "Account.Login")
			</span>
		</a>
	</div>

	@if (Model.CompareProductsEnabled)
	{
		<div class="shopbar-tool" id="shopbar-compare" data-target="#compare-tab">
			<a href="@Url.Action("CompareProducts", "Catalog")"  class="shopbar-button navbar-toggler" data-toggle="offcanvas" data-summary-href="@Url.Action("CartSummary", "ShoppingCart", new { compare = true })"
			   data-autohide="true" data-placement="@(isRtl ? "left" : "right")" data-fullscreen="false" data-disablescrolling="true" data-target="#offcanvas-cart">
				<span class="shopbar-button-icon">
					<i class="icm icm-repeat"></i>
					<span class='badge badge-pill label-cart-amount badge-@labelStyle' style="@(Model.CompareItemsCount == 0 ? "display:none" : "")" data-bind-to="CompareItemsCount">@Model.CompareItemsCount</span>
				</span>
				<span class="shopbar-button-label">
					<span>@T("Common.Shopbar.CompareProductsPartOne")</span><br />
					<strong>@T("Common.Shopbar.CompareProductsPartTwo")</strong>
				</span>
				<span class="shopbar-button-label-sm">
					@T("Common.Shopbar.Compare")
				</span>
			</a>
		</div>
	}

	@if (Model.WishlistEnabled)
	{
		<div class="shopbar-tool" id="shopbar-wishlist" data-target="#wishlist-tab">
			<a href="@Url.RouteUrl("Wishlist")" class="shopbar-button navbar-toggler" data-toggle="offcanvas" data-summary-href="@Url.Action("CartSummary", "ShoppingCart", new { wishlist = true })"
				data-autohide="true" data-placement="@(isRtl ? "left" : "right")" data-fullscreen="false" data-disablescrolling="true" data-target="#offcanvas-cart">
				<span class="shopbar-button-icon">
					<i class="icm icm-heart"></i>
					<span class='badge badge-pill label-cart-amount badge-@labelStyle' style="@(Model.WishlistItemsCount == 0 ? "display:none" : "")" data-bind-to="WishlistItemsCount">@Model.WishlistItemsCount</span>
				</span>
				<span class="shopbar-button-label">
					<span>@T("Common.Shopbar.WishlistPartOne")</span><br />
					<strong>@T("Common.Shopbar.WishlistPartTwo")</strong>
				</span>
				<span class="shopbar-button-label-sm">
					@T("Wishlist")
				</span>
			</a>
		</div>
	}

	@if (Model.ShoppingCartEnabled)
	{
		<div class="shopbar-tool" id="shopbar-cart" data-target="#cart-tab">
			<a href="@Url.RouteUrl("ShoppingCart")" class="shopbar-button navbar-toggler" data-toggle="offcanvas" data-summary-href="@Url.Action("CartSummary", "ShoppingCart", new { cart = true })"
			   data-autohide="true" data-placement="@(isRtl ? "left" : "right")" data-fullscreen="false" data-disablescrolling="true" data-target="#offcanvas-cart">
				<span class="shopbar-button-icon">
					<i class="icm icm-bag"></i>
					<span class='badge badge-pill label-cart-amount badge-@(labelStyle)' style="@(Model.CartItemsCount == 0 ? "display:none" : "")" data-bind-to="CartItemsCount">
						@Model.CartItemsCount
					</span>
				</span>
				<span class="shopbar-button-label">
					<span>@T("Common.Shopbar.BasketPartOne")</span><br />
					<strong>@T("Common.Shopbar.BasketPartTwo")</strong>
				</span>
				<span class="shopbar-button-label-sm">
					@T("Common.Shopbar.Basket")
				</span>
			</a>
		</div>
	}

    @{ Html.RenderWidget("shopbar_tools_after"); }

</div>

@using (Html.BeginZoneContent("aftercontent", key: "offcanvas-menu"))
{
	<aside id="offcanvas-menu" class="offcanvas offcanvas-overlay offcanvas-@(isRtl ? "right" : "left") offcanvas-shadow" data-blocker="true" data-overlay="true">
        <div class="offcanvas-content">
            <div id="offcanvas-menu-container" data-url="@(Url.Action("OffCanvas", "Menu"))">
                <!-- AJAX -->
            </div>
        </div>
	</aside>
}

@using (Html.BeginZoneContent("aftercontent", key: "offcanvas-cart"))
{
	<aside id="offcanvas-cart" class="offcanvas offcanvas-lg offcanvas-overlay offcanvas-@(isRtl ? "left" : "right") offcanvas-shadow" data-lg="true" data-blocker="true" data-overlay="true">
		<div class="offcanvas-content">
			@Html.Action("OffCanvasCart", "ShoppingCart", new { area = "" })
		</div>
	</aside>
}